# Generated by Django 4.0.5 on 2022-06-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_user_id_product_user_id_donor_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], default='OPEN', max_length=255),
        ),
    ]
